README.md, packages/examples/stories/index.stories.js, packages/storybook-addon-designs/src/config.ts, packages/storybook-addon-designs/src/index.ts, packages/storybook-addon-designs/src/register/components/Wrapper.tsx
Add the ability to attach more than one designs to a story.
Close #7 
[Preview](https://storybook-addon-designs-git-feature-multiple-designs.pocka.now.sh/?path=/story/examples-advanced--embed-multiple-designs)
[Preview (with tab names)](https://storybook-addon-designs-git-feature-multiple-designs.pocka.now.sh/?path=/story/examples-advanced--set-tab-names)
=> Multipe designs

packages/examples/stories/index.stories.js, packages/storybook-addon-designs/src/register/components/Wrapper.tsx
Fix bug that panel content does not update at all when changing to the story which does not have `withDeisgns` decorator nor `design` parameters.
Fix #14 
Tests in live example: <https://storybook-addon-designs-git-fix-addon-panel-persist.pocka.now.sh/?path=/story/tests-issues-14--do-not-persist-addon-panel-step-1>
=> Do not persist design panel on story changes

CHANGELOG.md, packages/examples/stories/tests/issues/39/index.stories.js, packages/storybook-addon-designs/src/config.ts, packages/storybook-addon-designs/src/register/components/Tabs.tsx, packages/storybook-addon-designs/src/register/components/Wrapper.tsx
Close #39 
Added `offscreen` option so users can control whether the tab content is rendered when the tab is not active. This option is always `false` regardless of the user input value when `type: "figma"`.
=> `offscreen` option

packages/storybook-addon-designs/tsconfig.json, yarn.lock
=> Transpile to ES5

packages/storybook-addon-designs/.gitignore, packages/storybook-addon-designs/package.json, packages/storybook-addon-designs/register.js, packages/storybook-addon-designs/tsconfig.json
=> Add CommonJS entrypoint

packages/examples-tab/.storybook/main.js, packages/examples/.storybook/main.js, packages/examples/package.json, packages/examples/stories/docs/advanced/docs.mdx, packages/examples/stories/internal/blocks/0.common.stories.mdx, packages/examples/stories/internal/blocks/1.design.stories.mdx, packages/examples/stories/internal/blocks/figma.stories.mdx, packages/examples/stories/internal/blocks/iframe.stories.mdx, packages/examples/stories/internal/blocks/image.stories.mdx, packages/examples/stories/internal/blocks/pdf.stories.mdx, packages/storybook-addon-designs/blocks.js, packages/storybook-addon-designs/package.json, packages/storybook-addon-designs/src/blocks.tsx, packages/storybook-addon-designs/src/lib.d.ts, packages/storybook-addon-designs/src/register/components/Wrapper.tsx, packages/storybook-addon-designs/src/register/containers/Wrapper.tsx, packages/storybook-addon-designs/src/register/index.tsx, yarn.lock
close #61 
Added Doc Blocks for each embed types.
- ~[ ] link~ Just write `[Text](url)` 🤣 
https://storybook-addon-designs-git-feature-doc-blocks.pocka.vercel.app/?path=/docs/docs-advanced-usage--embed-multiple-designs#doc-blocks
=> Doc Blocks

packages/storybook-addon-designs/src/register/components/Figma.tsx, packages/storybook-addon-designs/src/register/components/IFrame.tsx
#77 
Defer loading Figma preview because of a "`document.fullscreenEnabled` is not updated" problem, which causes the linked issue above. I left other `<iframe>`s as-is but maybe other sites need to defer as well.
=> Defer loading Figma preview

packages/examples/stories/tests/issues/81.stories.js, packages/storybook-addon-designs/src/register/components/IFrame.tsx
fix #81 
When embedding pages with no backgrounds, the "loading..." placeholder label would be visible. From the commit, the addon hides it when the iframe is loaded.
=> Do not show loading placeholder when iframe is loaded

packages/examples/stories/tests/issues/83.stories.js, packages/storybook-addon-designs/src/register/components/Tabs.tsx, packages/storybook-addon-designs/src/register/components/Wrapper.tsx
Fix #83.
Fixes key duplication between different stories.
[Preview Deploy: Tests / Issues / #83](https://storybook-addon-designs-4potv4b3h.vercel.app/?path=/story/tests-issues-83--story-2)
=> Use unique key for each tabs

packages/storybook-addon-designs/src/register/containers/Wrapper.tsx, packages/storybook-addon-designs/src/register/index.tsx
Issue: N/A
I saw a problem where the design wasn't loading on the initial story until I switched stories and switched back. When I looked at the addon source I found that it's reimplementing a bunch of state management that's already handled by Storybook's hook API. So I updated the code accordingly.
I ran the example in the monorepo to check the different examples, but I'm not sure I tested all cases. If you can test it or suggest the best way for me to test it, I'd be happy to follow up.
=> Simplify wrapper with storybook hooks API

packages/storybook-addon-designs/package.json, packages/storybook-addon-designs/src/register/components/Figspec.tsx, yarn.lock
Figspec will now present a footer with some metadata and link to the figma component, with a link to open in Figma:
=> feat: present footer with component url in figspec

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.md, packages/examples/stories/docs/figspec/README.stories.mdx, packages/examples/stories/internal/blocks/figma-spec.stories.mdx, packages/storybook-addon-designs/package.json, packages/storybook-addon-designs/src/blocks.tsx, packages/storybook-addon-designs/src/config.ts, packages/storybook-addon-designs/src/register/components/Wrapper.tsx, yarn.lock
Added `type: "figspec"` and Deprecated `type: "experimental-figspec"`. The latter will be removed on v7.0.
=> Stabilize Figspec integration

packages/storybook-addon-designs/src/register/index.tsx
fix #134 
Storybook does not support function title for the `<Tab>` component. Changed to always use the default tab name (`Design`) when `renderTarget` is set to `"tab"`.
- [Preview deploy (tab mode)](https://storybook-addon-designs-qn5yuylnq-pocka.vercel.app/tab/?path=/story/docs-figma-examples--embed-file)
=> Use static tab name for renderTarget=tab

packages/storybook-addon-designs/package.json
We require these at runtime, so they need to at least be
peerDependencies (if not normal dependencies).
Packagers such as Yarn PnP and pnpm use an unambiguous dependency
layout, where packages are only able to require their declared
dependencies. In order to consume dependencies fulfilled by our
ancestors in these scenarios, we have to declare them as
peerDependencies. This will cause the package manager to "forward"
matching dependencies declared by our parent.
=> fix: Add missing peer dependencies

packages/storybook-addon-designs/src/register/components/Tabs.tsx, packages/storybook-addon-designs/src/register/components/Wrapper.tsx, packages/storybook-addon-designs/src/register/containers/Wrapper.tsx, packages/storybook-addon-designs/src/register/index.tsx
Refer to the code comments and the commit comment for details.
close #153
=> Do not destroy rendered contents on addon tab changes

packages/storybook-addon-designs/src/index.ts
In Storybook 7.0, the export from `@storybook/addons` changed to only contain names exports.
The change in this PR is backwards compatible with 6.5, but necessary in Storybook 7.0, else the addon will not be registered.
=> fix: update storybook addons import for Storybook 7.0

packages/storybook-addon-designs/src/register/index.tsx
This PR updates the `addons` import within register, which was left out in the [previous Storybook 7 update](https://github.com/pocka/storybook-addon-designs/pull/160).
See: https://github.com/pocka/storybook-addon-designs/issues/172
=> Fix support for Storybook 7.0.0-alpha

packages/storybook-addon-designs/src/register/index.tsx
See https://github.com/storybookjs/storybook/pull/23792
<details>
<summary>📦 Published PR as canary version: <code>7.0.2--canary.207.ad30797.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install @storybook/addon-designs@7.0.2--canary.207.ad30797.0
yarn add @storybook/addon-designs@7.0.2--canary.207.ad30797.0
```
</details>
=> Don't use key anymore for rendering addon

CONTRIBUTING.md, packages/examples/stories/tests/issues/156.stories.tsx, packages/storybook-addon-designs/package.json, packages/storybook-addon-designs/src/register/components/ErrorBoundary.tsx, packages/storybook-addon-designs/src/register/components/IFrame.tsx, packages/storybook-addon-designs/src/register/components/Wrapper.tsx
Some URLs still refer old repo (`pocka/storybook-addon-designs`).
This patch is basically `s/pocka\/storybook-addon-designs/storybookjs\/addon-designs/g` except one with `FIXME:` comment.
=> Update repository URL to storybookjs/addon-designs

.github/workflows/deploy-ghpages.yml
This PR re-enables a GitHub Actions workflow that builds example Storybook then deploys it to GitHub Pages. I have also changed the deploy action to the new official action from third party one (5500a94c3923c945fc891f2bd801b3c5da625d39).
Fix #187.
=> Re-enable GitHub Pages deploy workflow

packages/examples/stories/internal/blocks/0.common.mdx, packages/storybook-addon-designs/src/blocks.tsx
closes #216 
Added `onCollapsedChange` property for `DocBlockBase` component, which is used by every Doc Block components.
This enables users (story authors) to persist collapsed state somewhere and restore it via `defaultCollapsed` property, in order to save users' screen estate.
I choose to use `onObjectVerb` naming style commonly used in DOM, but willing to change if official Storybook code/community has widely used style.
=> Add `onCollapsedChange` prop for Doc Block

.prettierignore
The file is auto generated thus should not be formatted.
This patch fixes ["Check code validity" workflow](https://github.com/storybookjs/addon-designs/actions/workflows/check-pushes.yml) failing.
=> Ignore auto generated CHANGELOG from formatting

.github/workflows/check-pushes.yml, .prettierignore, packages/examples/stories/tests/issues/239.stories.jsx, packages/storybook-addon-designs/src/manager/components/Figma.tsx, packages/storybook-addon-designs/src/manager/components/Figspec.tsx
close #239
Figma changed URL structure for the share URL from `"/file/..."` to `"/<anything>/..."`. This patch updates the URL checking regexp according to their updated [embed document](https://www.figma.com/developers/embed).
<details>
<summary>📦 Published PR as canary version: <code>8.0.3--canary.240.540483c.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install @storybook/addon-designs@8.0.3--canary.240.540483c.0
yarn add @storybook/addon-designs@8.0.3--canary.240.540483c.0
```
</details>
=> Support for the new Figma share URL

package-lock.json, packages/storybook-addon-designs/package.json
Reverts storybookjs/addon-designs#253
The PR has causing issues when using the `Figma` component in mdx like this example shows:
```mdx
import {Figma} from '@storybook/addon-designs/blocks';
import {Meta, Title} from '@storybook/blocks';
<Meta title="Documentation/Styles/Colors" />
<Title> Colors </Title>
<Figma
defaultCollapsed
url="{{insert any valid figma link}}"
/>
```
=> Revert "Remove react peer dependency"

packages/storybook-addon-designs/src/manager/components/Figma.tsx
Hey!
Figma has recently released embed kit v2 which provides enhanced security features as well abit more control and flexibility over the embeds.
this PR migrates the url according to the guide in https://www.figma.com/developers/embed#migrate
Thanks
=> feat(figma): migrate url to use embed kit v2
